import { createFileRoute, Link } from "@tanstack/react-router";
import { ScrollToTopButton } from "../components/ScrollToTopButton";
import { SiteHeader } from "../components/SiteHeader";
import { SiteFooter } from "../components/SiteFooter";

const EMAIL = "sohibcorp0706@gmail.com";
const UPDATED = "August 4, 2026";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Service — Scentwise" },
      {
        name: "description",
        content:
          "The rules for using Scentwise: acceptable use, accuracy of fragrance and price data, AI consultant limits, third-party links, intellectual property and liability.",
      },
      { property: "og:title", content: "Scentwise Terms of Service" },
      {
        property: "og:description",
        content: "Acceptable use, data accuracy, AI limits, third-party links and liability for the Scentwise site.",
      },
      { property: "og:url", content: "https://scentwisefragrances.lovable.app/terms" },
    ],
    links: [{ rel: "canonical", href: "https://scentwisefragrances.lovable.app/terms" }],
  }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <main className="min-h-screen bg-background text-foreground">
      <div className="scent-aura" aria-hidden="true" />
      <SiteHeader current="home" breadcrumb="Home → Terms of Service" />

      <div className="relative z-10 mx-auto max-w-[820px] px-5 pb-16 pt-4">
        <h1 className="font-serif text-4xl font-bold sm:text-5xl">Terms of Service</h1>
        <p className="mt-2 text-sm text-muted-foreground">Last updated: {UPDATED}</p>
        <p className="mt-4 text-lg text-muted-foreground">
          These terms govern your use of Scentwise, an independent fragrance discovery and education site operated by So
          Hib Corp in Toronto, Ontario, Canada. By using the site you agree to them. If you do not agree, please stop
          using the site.
        </p>

        <S title="1. What Scentwise provides">
          <p>
            Scentwise offers editorial content: a guided fragrance quiz, a directory of brand websites, comparisons of
            fragrance retailers, an educational hub and an AI consultant. We do not sell fragrance, hold inventory,
            process payments or ship anything. Every purchase you make happens on a third-party retailer's site under
            that retailer's own terms.
          </p>
        </S>

        <S title="2. No account, no fee">
          <p>
            The site is free and requires no registration. We may add, change or remove features, pages or fragrances at
            any time, and we may suspend the site for maintenance without notice.
          </p>
        </S>

        <S title="3. Accuracy of fragrance, brand and price information">
          <p>
            Note listings, longevity and projection bands, seasonal and occasion tags and price ranges are editorial
            judgements and estimates, not guarantees. Prices are shown as Canadian-dollar ranges and change constantly
            with supply, exchange rates and promotions. Formulations are also reformulated by brands without notice, so a
            bottle bought today may smell different from one reviewed a year ago. Always confirm current price,
            concentration and size on the retailer's own product page before purchasing.
          </p>
        </S>

        <S title="4. Recommendations are suggestions, not advice">
          <p>
            Match percentages express how closely a fragrance fits the preferences you entered under our scoring model.
            They are not a prediction that you will like a scent — skin chemistry, climate and personal memory dominate
            real-world experience. Nothing on this site is medical or dermatological advice; if you have sensitive skin,
            allergies or are pregnant, check the full ingredient list and consult a professional before use.
          </p>
        </S>

        <S title="5. The AI consultant">
          <p>
            The chat consultant is generated by a third-party language model and can be wrong, out of date or confidently
            inconsistent. Treat its output as a starting point to verify, not as fact. Do not submit sensitive personal
            information, credentials or payment details into the chat. We may rate-limit, restrict or withdraw the feature
            to control abuse and cost.
          </p>
        </S>

        <S title="6. Acceptable use">
          <p>
            You may read, share and link to our pages freely, and use them for personal, non-commercial purposes. You may
            not scrape or bulk-copy the database to build a competing product, resell our content, attempt to overload or
            break the site, probe it for vulnerabilities without permission, misuse the AI consultant to generate
            unlawful or abusive content, or misrepresent yourself as affiliated with Scentwise.
          </p>
        </S>

        <S title="7. Third-party links and advertising">
          <p>
            We link to brand and retailer websites for convenience. We do not control them and are not responsible for
            their content, pricing, authenticity claims, shipping, customs charges or customer service. Some links may be
            affiliate links, and the site displays advertising served by Google AdSense and other vendors, as described in
            our <Link to="/privacy" className="font-semibold text-primary underline">Privacy Policy</Link>. Ads are
            selected by those vendors and their presence is not an endorsement.
          </p>
        </S>

        <S title="8. Intellectual property">
          <p>
            The site's text, design, scoring logic and curated data are owned by Scentwise and protected by copyright.
            Brand names, product names and logos belong to their respective owners and are used descriptively for
            identification and commentary — nominative fair use, not a claim of affiliation, sponsorship or endorsement.
            Brief quotation with a link back is welcome; wholesale reproduction is not.
          </p>
        </S>

        <S title="9. Disclaimer and limitation of liability">
          <p>
            The site is provided "as is" and "as available", without warranties of any kind, express or implied, including
            merchantability, fitness for a particular purpose and non-infringement. To the fullest extent permitted by
            law, Scentwise and its contributors are not liable for any indirect, incidental or consequential loss, or for
            any loss arising from a purchase you make from a third-party retailer, from reliance on price or note data, or
            from use of the AI consultant. Where liability cannot be excluded, it is limited to CAD $100.
          </p>
        </S>

        <S title="10. Governing law and changes">
          <p>
            These terms are governed by the laws of the Province of Ontario and the applicable laws of Canada, and the
            courts of Ontario have jurisdiction, without limiting any mandatory consumer-protection rights you hold where
            you live. We may update these terms; the date at the top will change and continued use constitutes acceptance.
          </p>
        </S>

        <S title="11. Contact">
          <p>
            Questions about these terms, takedown requests or corrections:{" "}
            <a href={`mailto:${EMAIL}`} className="font-semibold text-primary underline">{EMAIL}</a>, or via our{" "}
            <Link to="/contact" className="font-semibold text-primary underline">contact page</Link>.
          </p>
        </S>
      </div>

      <SiteFooter />
      <ScrollToTopButton />
    </main>
  );
}

function S({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mt-10">
      <h2 className="font-serif text-2xl font-bold">{title}</h2>
      <div className="mt-3 space-y-4 text-base leading-relaxed text-muted-foreground">{children}</div>
    </section>
  );
}
